// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedSecProfUserNameString221 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedSecProfUserNameString221));
        
        string IMigrationMetadata.Id
        {
            get { return "202012280248099_addedSecProfUserNameString221"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
